# Generated by Django 5.1.6 on 2025-03-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_subject_description_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
