# Generated by Django 5.1.6 on 2025-03-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_class_year_student_age'),
    ]

    operations = [
        
        migrations.AddConstraint(
            model_name='class',
            constraint=models.CheckConstraint(condition=models.Q(('year__regex', '^\\d+$')), name='year_has_only_digits'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('grade',), name='unique_grade'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 0), ('age__lte', 18)), name='age_between_zero_and_eighteen'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('first_name__regex', '^[A-Z]')), name='first_name_student_starts_uppercase'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('last_name__regex', '^[A-Z]')), name='last_name_student_starts_uppercase'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('first_name__regex', '^[\\D]*$')), name='first_name_student_has_no_digits'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('last_name__regex', '^[\\D]*$')), name='last_name_student_has_no_digits'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_first_name_student'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '^[\\D]*$')), name='name_has_no_digits'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('first_name__regex', '^[A-Z]')), name='first_name_starts_uppercase'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('last_name__regex', '^[A-Z]')), name='last_name_starts_uppercase'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('first_name__regex', '^[\\D]*$')), name='first_name_has_no_digits'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('last_name__regex', '^[\\D]*$')), name='last_name_has_no_digits'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_first_name'),
        ),
    ]
